ALTER TABLE "roles" DROP COLUMN IF EXISTS "created_at";
ALTER TABLE "roles" DROP COLUMN IF EXISTS "updated_at";
ALTER TABLE "users" DROP COLUMN IF EXISTS "created_at";
ALTER TABLE "users" DROP COLUMN IF EXISTS "updated_at";